http:
    servers:
        - listen: 1231
          logger: true
          name: server_1231
          logger_path: ./logs/server_1231
          version: 0.0.1
          location:
            - path: /bancrecer/simf/1.0.0/operaciones
              method: POST
              response: ""
              status_code: 0
              headers:
                content_type: application/json
          chaos_injection:
            probability: 100
            status_code: 300
